panmanUtils_path: "/private/groups/corbettlab/petria/installs/panmap/build/bin/panmanUtils"
panmap_path: "/private/groups/corbettlab/petria/installs/panmap/build/bin/panmap"
swampy_path: "/private/groups/corbettlab/petria/installs/SWAMPy/src/simulate_metagenome.py"

# Number of replicates (i.e., random selection of sequences) for each condition
n_replicates: 2   # Integer

# Specify existing panman
# Use published panman: sars20000, ecoli1000, hiv20000, tb400, rsv4000, or klebs1000)
# Or use file prefix for any panman saved in resources folder in pipeline directory
tree: "rsv4000"   # String or list of strings

# Haplotype relative abundance (list; must sum to 1)
abundances:
  - [.5, .25, .25]  # One or multiple lists

# Select read simulator (iss, swampy)
simulator: "iss"  # String or list of strings
n_reads: 1000   # Integer or list of integers

iss_params:
  model: "miseq"  # String
  # Treat n_reads specified above as depth instead.
  use_depth: False   # If true, the actual number of reads will be calculated based on genome size & sequencing model read length.
  cpus: 8

swampy_params: 
  # Select sars ARTIC or Nimagen primer set (a1, a4, a5, n2)
  primer_set: "a5"  # String

panmap_params:  # Integer or list of integers for all panmap parameters except len_k_s_mers
  len_k_s_mers: 10 5 # Two numbers, len k and len s, separated by a space. Or a list of two numbers separated by a space. 
  check_frequency: 5
  redo_read_threshold: 0
  remove_iteration: 5
  cpus: 4
