# Number of replicates (i.e., random selection of sequences) for each condition
n_replicates: 2   # Integer

# Specify existing panman (sars, ecoli, hiv, tb, rsv, or klebs)
tree: "rsv"   # String or list of strings

# Haplotype relative abundance (list; must sum to 1)
abundances:
  - [.5, .25, .25]  # One or multiple lists
  - [1]

# Select read simulator (iss, swampy)
simulator: ["iss", "swampy"]  # String or list of strings
n_reads: 1000   # Integer or list of integers

iss_params:
  model: "miseq"  # String
  # Treat n_reads specified above as depth instead.
  use_depth: False   # If true, the actual number of reads will be calculated based on genome size & sequencing model read length.
  cpus: 8

swampy_params: 
  # Select sars ARTIC or Nimagen primer set (a1, a4, a5, n2)
  primer_set: "a5"  # String

panmap_params:  # Integer or list of integers for all panmap parameters
  len_k_mer: 10
  len_s_mer: 5
  check_frequency: 5
  redo_read_threshold: 0
  remove_iteration: 5
  cpus: 4
